int NUM_X=3;
int NUM_Y=3;
int  NUM_SPOT=NUM_X*NUM_Y;
int[] spots = new int[NUM_SPOT];

color BG=color(0,0,0);

int U=100;

import spacebrew.*;
Spacebrew sb;
String server="net.marcobrianza.it";
String name="9ColorSpotsP5";
String description ="Color Spots Generated by software";

String colorString="";
String spotString="";

 void setup(){
 size(U*NUM_X*2, U*NUM_Y*2);

 colorMode(RGB, 255);
 smooth();
 noStroke();
 ellipseMode(CENTER);
   
 frameRate(0.2);
   
  // instantiate the spacebrewConnection variable
  sb = new Spacebrew( this );
  // declare your publishers
  sb.addPublish("allSpots","string",spotString);
  sb.connect(server, name, description );  
  
 }
 
void draw(){
 //float r=random(1,20);
 //frameRate(1/r);
  
 int Ri=int(random(NUM_SPOT));
 int ci=int(random(0,16*16*16));

 spots[Ri]=(ci);

 drawSpots();
 sendColors();

 } 
 
 
 void sendColors(){
  String cs="";
  for (int i=0; i<NUM_SPOT;i++){
    cs=cs+spots[i]+",";
 }
  println("Sending allSpots:",cs);
  sb.send("allSpots",cs);
 
 }
 
 
 
 void drawSpots(){
    background(BG);
  for (int i=0; i<NUM_SPOT; i++){
    int x=(i % NUM_X);
    int y=int(i/NUM_Y);
    int cx=x*U*2 + U;
    int cy=y*U*2+U;
    //println( x,y);
    fill(ci2c(spots[i]));
     ellipse(cx,cy,U,U); 
  }
 }
 
color ci2c(int ci){
int r,g,b;

   r=ci & 0x000F;
   g=ci>>4 & 0x000F;
   b=ci>>8 & 0x000F;  
   return color(r*16,g*16,b*16); 
  
}
